
name: Upload Open API

on:
  push:
    branches:
      - "master"

jobs:
  upload_api:
    runs-on: ubuntu-latest
    steps:
      - uses: mfish33/reusable-action-poc
        with:
          file-path: open-api.json
          api-key: blah blah blah
