
name: Upload Open API

on:
  push:
    branches:
      - "master"

jobs:
  upload_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mfish33/reusable-action-poc@v1
        with:
          file-path: open-api.json
          api-key: blah blah blah